# Generated by Django 3.0.1 on 2020-01-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_2',
            field=models.TextField(),
        ),
    ]
