# Generated by Django 3.0.1 on 2020-01-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20200112_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='fart', max_length=32),
            preserve_default=False,
        ),
    ]
